#!/usr/bin/env python3
"""Build the Salesforce API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Reports & Dashboards': 'Reports & Dash',
    'Einstein Platform': 'Einstein Plat.',
    'Einstein Prediction': 'Einstein Pred.',
    'Mktg Cloud REST': 'MC REST',
    'Mktg Cloud SOAP': 'MC SOAP',
    'Commerce OCAPI': 'Commerce OCAPI',
    'Change Data Capture': 'Change Data Capture',
    'Field Service': 'Field Service',
    'Financial Svcs': 'Financial Svcs',
    'Platform Events': 'Platform Events',
    'Analytics REST': 'Analytics REST',
}

LINES = [
    {
        "name": 'Core REST/SOAP',
        "color": '#00A1E0',
        "stations": [
        ('REST', (270, 195)),
        ('SOAP', (420, 175)),
        ('Bulk', (560, 165)),
        ('Bulk v2', (700, 165)),
        ('Streaming', (840, 175)),
        ('Tooling', (980, 200)),
        ],
    },
    {
        "name": 'Metadata & Composite',
        "color": '#0E9D6E',
        "stations": [
        ('Metadata', (270, 310)),
        ('Connect', (430, 285)),
        ('Composite', (590, 285)),
        ('Apex REST', (760, 285)),
        ('UI', (920, 310)),
        ],
    },
    {
        "name": 'Analytics & Reports',
        "color": '#E68B1F',
        "stations": [
        ('Analytics REST', (270, 425)),
        ('Reports & Dashboards', (490, 405)),
        ('Pub/Sub', (700, 405)),
        ('Platform Events', (900, 425)),
        ],
    },
    {
        "name": 'Einstein AI',
        "color": '#7B3FE4',
        "closed": True,
        "stations": [
        ('Einstein Platform', (820, 510)),
        ('Einstein Prediction', (905, 580)),
        ('Models', (820, 660)),
        ('Agentforce', (735, 580)),
        ],
    },
    {
        "name": 'Industry Clouds',
        "color": '#1E5BD0',
        "stations": [
        ('Field Service', (270, 540)),
        ('Health', (430, 515)),
        ('Financial Svcs', (610, 515)),
        ('Experience', (790, 540)),
        ],
    },
    {
        "name": 'Marketing & Commerce',
        "color": '#C5318B',
        "stations": [
        ('Mktg Cloud REST', (270, 660)),
        ('Mktg Cloud SOAP', (430, 635)),
        ('Pardot', (610, 635)),
        ('Commerce OCAPI', (790, 635)),
        ('Shopper', (940, 660)),
        ],
    },
    {
        "name": 'Data & Integration',
        "color": '#5A6275',
        "stations": [
        ('GraphQL', (270, 770)),
        ('Change Data Capture', (440, 745)),
        ('Data Cloud', (640, 745)),
        ('MuleSoft', (820, 745)),
        ('Tableau', (970, 770)),
        ],
    },
]

URL_OVERRIDES = {
    'REST': 'https://apis.apis.io/apis/salesforce/salesforce-rest-api/',
    'SOAP': 'https://apis.apis.io/apis/salesforce/salesforce-soap-api/',
    'Bulk': 'https://apis.apis.io/apis/salesforce/salesforce-bulk-api/',
    'Bulk v2': 'https://apis.apis.io/apis/salesforce/salesforce-bulk-api-2/',
    'Streaming': 'https://apis.apis.io/apis/salesforce/salesforce-streaming-api/',
    'Metadata': 'https://apis.apis.io/apis/salesforce/salesforce-metadata-api/',
    'Tooling': 'https://apis.apis.io/apis/salesforce/salesforce-tooling-api/',
    'Connect': 'https://apis.apis.io/apis/salesforce/salesforce-connect-api/',
    'Analytics REST': 'https://apis.apis.io/apis/salesforce/salesforce-analytics-rest-api/',
    'Reports & Dashboards': 'https://apis.apis.io/apis/salesforce/salesforce-reports-and-dashboards-rest-api/',
    'Einstein Platform': 'https://apis.apis.io/apis/salesforce/salesforce-einstein-platform-services-api/',
    'Einstein Prediction': 'https://apis.apis.io/apis/salesforce/salesforce-einstein-prediction-service-api/',
    'GraphQL': 'https://apis.apis.io/apis/salesforce/salesforce-graphql-api/',
    'Pub/Sub': 'https://apis.apis.io/apis/salesforce/salesforce-pub-sub-api/',
    'Platform Events': 'https://apis.apis.io/apis/salesforce/salesforce-platform-events-api/',
    'Change Data Capture': 'https://apis.apis.io/apis/salesforce/salesforce-change-data-capture-api/',
    'UI': 'https://apis.apis.io/apis/salesforce/salesforce-ui-api/',
    'Composite': 'https://apis.apis.io/apis/salesforce/salesforce-composite-api/',
    'Apex REST': 'https://apis.apis.io/apis/salesforce/salesforce-apex-rest-api/',
    'Data Cloud': 'https://apis.apis.io/apis/salesforce/salesforce-data-cloud-api/',
    'Mktg Cloud REST': 'https://apis.apis.io/apis/salesforce/salesforce-marketing-cloud-rest-api/',
    'Mktg Cloud SOAP': 'https://apis.apis.io/apis/salesforce/salesforce-marketing-cloud-soap-api/',
    'Pardot': 'https://apis.apis.io/apis/salesforce/salesforce-pardot-api/',
    'Commerce OCAPI': 'https://apis.apis.io/apis/salesforce/salesforce-commerce-cloud-ocapi/',
    'Shopper': 'https://apis.apis.io/apis/salesforce/salesforce-commerce-cloud-shopper-apis/',
    'Field Service': 'https://apis.apis.io/apis/salesforce/salesforce-field-service-api/',
    'Health': 'https://apis.apis.io/apis/salesforce/salesforce-health-cloud-api/',
    'Financial Svcs': 'https://apis.apis.io/apis/salesforce/salesforce-financial-services-cloud-api/',
    'Experience': 'https://apis.apis.io/apis/salesforce/salesforce-experience-cloud-api/',
    'MuleSoft': 'https://apis.apis.io/apis/salesforce/salesforce-mulesoft-anypoint-platform-api/',
    'Tableau': 'https://apis.apis.io/apis/salesforce/salesforce-tableau-rest-api/',
    'Agentforce': 'https://apis.apis.io/apis/salesforce/salesforce-agentforce-agent-api/',
    'Models': 'https://apis.apis.io/apis/salesforce/salesforce-models-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Salesforce API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: salesforce/openapi · github.com/api-evangelist/salesforce',
        out_dir=Path(__file__).resolve().parent,
        out_basename='salesforce-subway-map',
        provider_id='salesforce',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
