openapi: 3.1.0
info:
  title: Salesforce Bulk API 2.0 Abort Info API
  description: 'Salesforce Bulk API 2.0 is a simplified, REST-based interface for bulk data operations that improves on the original Bulk API. It uses a straightforward job model and supports CSV format for ingest and query jobs, enabling processing of millions of records asynchronously.

    '
  version: v63.0
  contact:
    name: Salesforce Developers
    url: https://developer.salesforce.com/
  license:
    name: Salesforce Developer Terms
    url: https://www.salesforce.com/company/legal/agreements/
servers:
- url: https://{instance}.salesforce.com/services/data/v{version}/jobs
  description: Salesforce Bulk API 2.0 jobs endpoint
  variables:
    instance:
      default: yourInstance
      description: 'The Salesforce instance identifier (e.g., na1, eu3, or a My Domain subdomain like mycompany).

        '
    version:
      default: '63.0'
      description: 'The Salesforce API version number (e.g., 63.0). Use the latest supported version for new integrations.

        '
security:
- BearerAuth: []
tags:
- name: Info
paths:
  /services/oauth2/userinfo:
    parameters: []
    get:
      tags:
      - Info
      summary: Salesforce Get User Info
      description: This requests uses an access token to get user information from Salesforce using the standard `/userinfo` endpoint.
      operationId: GetUserInfo
      parameters:
      - name: Authorization
        in: header
        description: Replace <token> with your access token
        required: true
        schema:
          type: string
          examples:
          - Bearer <Token>
        example: example_value
      - name: Content-Type
        in: header
        description: ''
        required: true
        schema:
          const: application/json
          type: string
          examples:
          - application/json
        example: example_value
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://login.salesforce.com
        variables: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /data/v64.0/jobs/query/:
    parameters: []
    get:
      tags:
      - Info
      summary: Salesforce Get Job Info Query
      operationId: GetJobInfoQuery
      parameters: []
      responses:
        '200':
          description: OK
          headers:
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: Fri, 17 Nov 2023 16:13:43 GMT
            Strict-Transport-Security:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: max-age=63072000; includeSubDomains
            X-Content-Type-Options:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: nosniff
            X-XSS-Protection:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: 1; mode=block
            X-Robots-Tag:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: none
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: no-cache,must-revalidate,max-age=0,no-store,private
            Sforce-Limit-Info:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: api-usage=2/15000
            Vary:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: Accept-Encoding
            Content-Encoding:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: gzip
            Transfer-Encoding:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: chunked
          content:
            application/json;charset=UTF-8:
              schema:
                allOf:
                - $ref: '#/components/schemas/SuccessfulGetJobInfoQuery'
                - examples:
                  - id: 750...
                    operation: insert
                    object: Account
                    createdById: 005...
                    createdDate: <datetime>
                    systemModstamp: <datetime>
                    state: Open
                    concurrencyMode: Parallel
                    contentType: CSV
                    apiVersion: 58
                    jobType: Classic
                    retries: 0
                    totalProcessingTime: 0
                    apiActiveProcessingTime: 0
                    apexProcessingTime: 0
                contentMediaType: application/json;charset=UTF-8
              example:
                id: 750...
                operation: insert
                object: Account
                createdById: 005...
                createdDate: <datetime>
                systemModstamp: <datetime>
                state: Open
                concurrencyMode: Parallel
                contentType: CSV
                apiVersion: 58
                jobType: Classic
                retries: 0
                totalProcessingTime: 0
                apiActiveProcessingTime: 0
                apexProcessingTime: 0
      deprecated: false
      servers:
      - url: https://services
        variables: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /data/v64.0/jobs/ingest/:
    parameters: []
    get:
      tags:
      - Info
      summary: Salesforce Get Job Info
      operationId: GetJobInfo
      parameters: []
      responses:
        '200':
          description: OK
          headers:
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: Mon, 20 Nov 2023 15:03:34 GMT
            Strict-Transport-Security:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: max-age=63072000; includeSubDomains
            X-Content-Type-Options:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: nosniff
            X-XSS-Protection:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: 1; mode=block
            X-Robots-Tag:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: none
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: no-cache,must-revalidate,max-age=0,no-store,private
            Sforce-Limit-Info:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: api-usage=8/15000
            Vary:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: Accept-Encoding
            Content-Encoding:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: gzip
            Transfer-Encoding:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: chunked
          content:
            application/json;charset=UTF-8:
              schema:
                allOf:
                - $ref: '#/components/schemas/SuccessfulGetJobInfo'
                - examples:
                  - id: 750...
                    operation: insert
                    object: Asset
                    createdById: 005...
                    createdDate: <datetime>
                    systemModstamp: <datetime>
                    state: JobComplete
                    concurrencyMode: Parallel
                    contentType: CSV
                    apiVersion: 58
                    jobType: V2Ingest
                    lineEnding: LF
                    columnDelimiter: COMMA
                    numberRecordsProcessed: 1
                    numberRecordsFailed: 1
                    retries: 0
                    totalProcessingTime: 100
                    apiActiveProcessingTime: 43
                    apexProcessingTime: 0
                contentMediaType: application/json;charset=UTF-8
              example:
                id: 750...
                operation: insert
                object: Asset
                createdById: 005...
                createdDate: <datetime>
                systemModstamp: <datetime>
                state: JobComplete
                concurrencyMode: Parallel
                contentType: CSV
                apiVersion: 58
                jobType: V2Ingest
                lineEnding: LF
                columnDelimiter: COMMA
                numberRecordsProcessed: 1
                numberRecordsFailed: 1
                retries: 0
                totalProcessingTime: 100
                apiActiveProcessingTime: 43
                apexProcessingTime: 0
      deprecated: false
      servers:
      - url: https://services
        variables: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /oauth2/userinfo:
    parameters: []
    get:
      tags:
      - Info
      summary: Salesforce User Info
      operationId: GetUserInfo1
      parameters:
      - name: Content-Type
        in: header
        description: ''
        required: true
        schema:
          const: application/json
          type: string
          examples:
          - application/json
        example: example_value
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://services
        variables: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    SuccessfulGetJobInfo:
      title: SuccessfulGetJobInfo
      required:
      - id
      - operation
      - object
      - createdById
      - createdDate
      - systemModstamp
      - state
      - concurrencyMode
      - contentType
      - apiVersion
      - jobType
      - lineEnding
      - columnDelimiter
      - numberRecordsProcessed
      - numberRecordsFailed
      - retries
      - totalProcessingTime
      - apiActiveProcessingTime
      - apexProcessingTime
      type: object
      properties:
        id:
          type: string
          example: abc123
        operation:
          type: string
          example: example_value
        object:
          type: string
          example: example_value
        createdById:
          type: string
          example: '500123'
        createdDate:
          type: string
          example: example_value
        systemModstamp:
          type: string
          example: example_value
        state:
          type: string
          example: example_value
        concurrencyMode:
          type: string
          example: example_value
        contentType:
          type: string
          example: example_value
        apiVersion:
          type: integer
          contentEncoding: int32
          example: 10
        jobType:
          type: string
          example: example_value
        lineEnding:
          type: string
          example: example_value
        columnDelimiter:
          type: string
          example: example_value
        numberRecordsProcessed:
          type: integer
          contentEncoding: int32
          example: 10
        numberRecordsFailed:
          type: integer
          contentEncoding: int32
          example: 10
        retries:
          type: integer
          contentEncoding: int32
          example: 10
        totalProcessingTime:
          type: integer
          contentEncoding: int32
          example: 1700000000000
        apiActiveProcessingTime:
          type: integer
          contentEncoding: int32
          example: 1700000000000
        apexProcessingTime:
          type: integer
          contentEncoding: int32
          example: 1700000000000
      examples:
      - id: 750...
        operation: insert
        object: Asset
        createdById: 005...
        createdDate: <datetime>
        systemModstamp: <datetime>
        state: JobComplete
        concurrencyMode: Parallel
        contentType: CSV
        apiVersion: 58
        jobType: V2Ingest
        lineEnding: LF
        columnDelimiter: COMMA
        numberRecordsProcessed: 1
        numberRecordsFailed: 1
        retries: 0
        totalProcessingTime: 100
        apiActiveProcessingTime: 43
        apexProcessingTime: 0
    SuccessfulGetJobInfoQuery:
      title: SuccessfulGetJobInfoQuery
      required:
      - id
      - operation
      - object
      - createdById
      - createdDate
      - systemModstamp
      - state
      - concurrencyMode
      - contentType
      - apiVersion
      - jobType
      - retries
      - totalProcessingTime
      - apiActiveProcessingTime
      - apexProcessingTime
      type: object
      properties:
        id:
          type: string
          example: abc123
        operation:
          type: string
          example: example_value
        object:
          type: string
          example: example_value
        createdById:
          type: string
          example: '500123'
        createdDate:
          type: string
          example: example_value
        systemModstamp:
          type: string
          example: example_value
        state:
          type: string
          example: example_value
        concurrencyMode:
          type: string
          example: example_value
        contentType:
          type: string
          example: example_value
        apiVersion:
          type: integer
          contentEncoding: int32
          example: 10
        jobType:
          type: string
          example: example_value
        retries:
          type: integer
          contentEncoding: int32
          example: 10
        totalProcessingTime:
          type: integer
          contentEncoding: int32
          example: 1700000000000
        apiActiveProcessingTime:
          type: integer
          contentEncoding: int32
          example: 1700000000000
        apexProcessingTime:
          type: integer
          contentEncoding: int32
          example: 1700000000000
      examples:
      - id: 750...
        operation: insert
        object: Account
        createdById: 005...
        createdDate: <datetime>
        systemModstamp: <datetime>
        state: Open
        concurrencyMode: Parallel
        contentType: CSV
        apiVersion: 58
        jobType: Classic
        retries: 0
        totalProcessingTime: 0
        apiActiveProcessingTime: 0
        apexProcessingTime: 0
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: 'OAuth 2.0 Bearer token obtained from the Salesforce OAuth 2.0 token endpoint. Include this token in the Authorization header as "Bearer {access_token}".

        '
